steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/auth-api:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/auth-api:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'auth-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/auth-api:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances'
      - '${_INSTANCE_CONNECTION_NAME}'
      - '--set-env-vars'
      - 'NODE_ENV=production,DB_USER=${_DB_USER},DB_NAME=${_DB_NAME},INSTANCE_CONNECTION_NAME=${_INSTANCE_CONNECTION_NAME}'
      - '--set-secrets'
      - 'DB_PASSWORD=auth-db-password:latest,JWT_SECRET=jwt-secret:latest'

images:
  - 'gcr.io/$PROJECT_ID/auth-api:$COMMIT_SHA'

substitutions:
  _REGION: us-central1
  _INSTANCE_CONNECTION_NAME: ${PROJECT_ID}:${_REGION}:auth-db-instance